<?php
declare(strict_types=1);
$data=json_decode((string)file_get_contents(__DIR__.'/calculator-data.json'),true);
$tool=isset($_GET['tool'])?(string)$_GET['tool']:'income';
$service=null;
foreach($data as $item){if(($item['t']??'')===$tool){$service=$item;break;}}
if(!$service){http_response_code(404);$service=['t'=>'404','name'=>'계산기를 찾을 수 없습니다','copy'=>'요청한 계산기 주소를 확인해주세요.','description'=>'요청한 계산기 페이지가 없습니다.','category'=>'돈'];}
$name=$service['name'];$category=$service['category'];$copy=$service['copy'];$detail=$service['description'];
$title=$name.' 계산기 | '.$detail.' | 돈시간';
$desc='돈시간 '.$name.' 계산기입니다. '.$detail.' 입력값을 바탕으로 결과를 확인할 수 있습니다.';
$canonical='https://dontime.kr/calculator.php?tool='.rawurlencode($tool);
function h($s){return htmlspecialchars((string)$s,ENT_QUOTES,'UTF-8');}
$related=[];foreach($data as $item){if(count($related)>=6)break;if($item['t']!==$tool&&$item['category']===$category)$related[]=$item;}
?><!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="index,follow"><meta name="description" content="<?=h($desc)?>"><link rel="canonical" href="<?=h($canonical)?>"><meta property="og:type" content="website"><meta property="og:site_name" content="돈시간"><meta property="og:title" content="<?=h($title)?>"><meta property="og:description" content="<?=h($desc)?>"><meta property="og:url" content="<?=h($canonical)?>"><meta property="og:locale" content="ko_KR"><title><?=h($title)?></title>
<script type="application/ld+json"><?=json_encode(['@context'=>'https://schema.org','@type'=>'WebApplication','name'=>$name.' 계산기','url'=>$canonical,'description'=>$desc,'applicationCategory'=>'CalculatorApplication','operatingSystem'=>'Web'],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?></script>
<script type="application/ld+json"><?=json_encode(['@context'=>'https://schema.org','@type'=>'BreadcrumbList','itemListElement'=>[['@type'=>'ListItem','position'=>1,'name'=>'돈시간','item'=>'https://dontime.kr/'],['@type'=>'ListItem','position'=>2,'name'=>$category],['@type'=>'ListItem','position'=>3,'name'=>$name.' 계산기','item'=>$canonical]]],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?></script>
<style>*{box-sizing:border-box}body{margin:0;background:#f6f7f9;color:#17191c;font-family:Arial,"Noto Sans KR",sans-serif}.wrap{max-width:900px;margin:auto;padding:28px 18px 60px}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}.logo{font-size:24px;font-weight:900}.home{color:#666;text-decoration:none;font-size:13px}.breadcrumb{font-size:12px;color:#777;margin-bottom:16px}.breadcrumb a{color:#666}.hero,.info,.related{background:#fff;border:1px solid #e2e5e9;border-radius:18px;padding:24px;margin-bottom:16px}.hero h1{font-size:30px;margin:0 0 9px;letter-spacing:-1px}.hero p,.info p{color:#555;line-height:1.75;font-size:14px}.cta{display:inline-block;padding:11px 15px;border-radius:10px;background:#17191c;color:#fff;text-decoration:none;font-weight:800;font-size:13px}.related h2,.info h2{font-size:18px;margin:0 0 9px}.links{display:flex;flex-wrap:wrap;gap:8px}.links a{padding:8px 10px;background:#f4f5f7;border-radius:9px;color:#555;text-decoration:none;font-size:12px}.note{padding:12px 14px;border-radius:10px;background:#f7f8fa;border:1px solid #e6e8eb;color:#666;font-size:12px;line-height:1.6}footer{margin-top:28px;padding-top:18px;border-top:1px solid #ddd;color:#888;font-size:12px}footer a{color:#666;margin-right:12px}</style></head><body><main class="wrap"><div class="top"><strong class="logo">돈시간</strong><a class="home" href="/">← 전체 계산기</a></div><nav class="breadcrumb" aria-label="사이트 이동 경로"><a href="/">돈시간</a> › <span><?=h($category)?></span> › <span><?=h($name)?> 계산기</span></nav><section class="hero"><h1><?=h($name)?> 계산기</h1><p><?=h($copy)?> <?=h($detail)?></p><a class="cta" href="/?tool=<?=rawurlencode($tool)?>">계산기 바로 사용하기 →</a></section><section class="info"><h2><?=h($name)?> 계산기 안내</h2><p>돈시간은 생활 속에서 자주 필요한 돈·시간 계산을 빠르게 확인할 수 있도록 계산기를 제공합니다. 이 페이지에서는 <?=h($name)?> 계산기의 용도와 계산 기준을 확인한 뒤 바로 계산기로 이동할 수 있습니다.</p><p><?=h($detail)?></p><div class="note">계산 결과는 입력한 값과 서비스에 구현된 계산 기준에 따른 참고용 결과입니다. 세금·금융·노무·건강처럼 실제 제도나 개인 조건에 따라 달라지는 항목은 적용 시점의 공식 기준을 함께 확인해주세요.</div></section><?php if($related): ?><section class="related"><h2><?=h($category)?> 관련 계산기</h2><div class="links"><?php foreach($related as $item): ?><a href="calculator.php?tool=<?=rawurlencode($item['t'])?>"><?=h($item['name'])?> 계산기</a><?php endforeach; ?></div></section><?php endif; ?><footer>돈시간 · <a href="/">전체 계산기</a><a href="calendar.php">달력</a><a href="about.html">서비스 안내</a><a href="privacy.html">개인정보처리방침</a><a href="terms.html">이용약관</a><a href="contact.html">문의</a></footer></main></body></html>